### ISSUE TITLE
Details about VOC: 15-5s

### ISSUE THREAD

**Issue by LIUZIJING-CHN** [LTTM/SDR#9]
First of all, thank you for your code! You've made a brilliant work!
Since I am a beginner in increment learning, I have a question in VOC task :15-5s:

If I want to learn the second task: which means `opt.step = 2`, but I have no pretrained model for task 0 and task 1, how should I run the project? Or should I first follow the sequential training stage: task 0->task 1->task 2?

Hope you can solve my doubt, Thanks a lot!

**Comment by umbertomichieli** [comment]
Hi, 
the VOC task 15-5s worklow is as follow:
- step 0: you first learn the initial 15 classes, then you save the model (M0)
- step 1: you start from the model M0 and you learn the 16th class. You save the model (M1)
- step 2: you start from the model M1 and you learn the 17th class. You save the model (M2)
- ...

So, in order to run the second task you should run all the previous ones.
Kind Regards
